<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .info {
            font-size: 11px;
            color: #666;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            border: 1px solid #ccc;
            padding: 8px;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            font-size: 10px;
            color: #999;
            margin-top: 30px;
            text-align: center;
        }
        .note {
            font-size: 10px;
            color: #666;
            font-style: italic;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">SRS-MartPlace-10</div>
        <div class="title">Laporan Daftar Toko Berdasarkan Lokasi Propinsi</div>
        <div class="info">
            Tanggal dibuat: {{ \Carbon\Carbon::now()->format('d-m-Y') }} oleh {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">No</th>
                <th style="width: 35%;">Nama Toko</th>
                <th style="width: 35%;">Nama PIC</th>
                <th style="width: 25%;">Propinsi</th>
            </tr>
        </thead>
        <tbody>
            @php
                // Group by province and sort
                $tablePrefix = config('laravolt.indonesia.table_prefix', 'indonesia_');
                $provincesTable = $tablePrefix . 'provinces';
                $groupedSellers = collect($data)
                    ->groupBy(function ($seller) use ($provincesTable) {
                        return \DB::table($provincesTable)
                            ->where('code', $seller->province_id)
                            ->value('name') ?? $seller->province_id;
                    })
                    ->sortKeys();
                $counter = 0;
            @endphp
            @forelse($groupedSellers as $province => $sellers)
                @foreach($sellers as $seller)
                    @php $counter++ @endphp
                    <tr>
                        <td>{{ $counter }}</td>
                        <td>{{ $seller->store_name }}</td>
                        <td>{{ $seller->user->name ?? 'N/A' }}</td>
                        <td>{{ $province }}</td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="4" style="text-align: center;">Tidak ada data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="note">
        ***) Data diurutkan berdasarkan propinsi
    </div>

    <div class="footer">
        Generated by SRS-MartPlace System
    </div>
</body>
</html>
