<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .info {
            font-size: 11px;
            color: #666;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            border: 1px solid #ccc;
            padding: 8px;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            font-size: 10px;
            color: #999;
            margin-top: 30px;
            text-align: center;
        }
        .note {
            font-size: 10px;
            color: #666;
            font-style: italic;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">SRS-MartPlace-11</div>
        <div class="title">Laporan Daftar Produk Berdasarkan Rating</div>
        <div class="info">
            Tanggal dibuat: {{ \Carbon\Carbon::now()->format('d-m-Y') }} oleh {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">No</th>
                <th style="width: 18%;">Produk</th>
                <th style="width: 12%;">Kategori</th>
                <th style="width: 12%;">Harga</th>
                <th style="width: 8%;">Rating</th>
                <th style="width: 22%;">Nama Toko</th>
                <th style="width: 23%;">Propinsi</th>
            </tr>
        </thead>
        <tbody>
            @php
                $counter = 0;
            @endphp
            @forelse($data as $product)
                @php 
                    $counter++;
                    // Get reviewer's province from reviews (where rating comes from)
                    $reviewerProvince = $product->reviewer_province ?? 'N/A';
                @endphp
                <tr>
                    <td>{{ $counter }}</td>
                    <td>{{ substr($product->name, 0, 30) }}{{ strlen($product->name) > 30 ? '...' : '' }}</td>
                    <td>{{ $product->category?->name ?? 'N/A' }}</td>
                    <td>Rp {{ number_format($product->price, 0, ',', '.') }}</td>
                    <td>{{ number_format($product->avg_rating, 1) }}/5</td>
                    <td>{{ $product->seller?->store_name ?? 'N/A' }}</td>
                    <td>{{ $reviewerProvince }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">Tidak ada data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="note">
        ***) Propinsi diisikan propinsi pemberi rating
    </div>

    <div class="footer">
        Generated by SRS-MartPlace System
    </div>
</body>
</html>
